include $(root)/tools/xml_stream/Makefile.include

littlem_to_xml_dependencies = \
	$(root)/tools/littlem_to_xml/littlem_to_xml.py \
	$(xml_stream_dependencies)

command_littlem_to_xml = PYTHONPATH=$(root)/tools/xml_stream/ python3 $(root)/tools/littlem_to_xml/littlem_to_xml.py
