root = ../..

default: all

all: all-recursive

all-here: 

all-recursive: 

check: 

clean: clean-recursive

clean-here: 

clean-recursive: clean-here

.PHONY: default all all-here all-recursive check clean clean-here clean-recursive
