arxadd_dependencies = \
	$(root)/tools/pyarx/arxadd.py \
	$(root)/tools/pyarx/arx.py

arxget_dependencies = \
	$(root)/tools/pyarx/arxget.py \
	$(root)/tools/pyarx/arx.py

arxtouch_dependencies = \
	$(root)/tools/pyarx/arxtouch.py \
	$(root)/tools/pyarx/arx.py

command_arxadd = python3 $(root)/tools/pyarx/arxadd.py

command_arxget = python3 $(root)/tools/pyarx/arxget.py

command_arxtouch = python3 $(root)/tools/pyarx/arxtouch.py
