generate_cpp_resource_constants_check-dependencies: 
	@if [ x`which $(PYTHON)` = x ]; then \
	    echo -e "\nYour system is missing the $(PYTHON) interpreter.\nIn order to use the generate_cpp_resource_constants tool you will need to install it on your system.\n"; false; \
	fi

generate_cpp_resource_constants_dependencies = \
	$(PYTHON_configuration) \
	$(root)/tools/generate_cpp_resource_constants/generate_cpp_resource_constants.py

command_generate_cpp_resource_constants = $(PYTHON) $(root)/tools/generate_cpp_resource_constants/generate_cpp_resource_constants.py

.PHONY: generate_cpp_resource_constants-check-dependencies
