subdir('tools')

manifest_json_configuration = configuration_data(
  {
    'AMMUNITION_CLASSES_LIGHT_GAUSS_AMMUNITION': meson.current_source_dir() / '.data/ammunition_class_light_gauss_ammunition.data',
    'BATTERY_CLASSES_LIGHT_BATTERY': meson.current_source_dir() / '.data/battery_class_light_battery.data',
    'COMMODITY_CLASSES_EQUIPMENT': meson.current_source_dir() / '.data/commodity_class_equipment.data',
    'COMMODITY_CLASSES_FOOD': meson.current_source_dir() / '.data/commodity_class_food.data',
    'COMMODITY_CLASSES_FUEL': meson.current_source_dir() / '.data/commodity_class_fuel.data',
    'COMMODITY_CLASSES_INDUSTRIAL': meson.current_source_dir() / '.data/commodity_class_industrial.data',
    'COMMODITY_CLASSES_LUXURY_GOODS': meson.current_source_dir() / '.data/commodity_class_luxury_goods.data',
    'COMMODITY_CLASSES_MEDICAL_SUPPLIES': meson.current_source_dir() / '.data/commodity_class_medical_supplies.data',
    'COMMODITY_CLASSES_METAL': meson.current_source_dir() / '.data/commodity_class_metal.data',
    'ENERGY_PROJECTILE_WEAPON_CLASSES_LIGHT_GAUSS_CANNON': meson.current_source_dir() / '.data/energy_projectile_weapon_class_light_gauss_cannon.data',
    'ENERGY_PROJECTILE_WEAPON_CLASSES_LIGHT_LASER': meson.current_source_dir() / '.data/energy_projectile_weapon_class_light_laser.data',
    'ENERGY_PROJECTILE_WEAPON_CLASSES_MEDIUM_LASER': meson.current_source_dir() / '.data/energy_projectile_weapon_class_medium_laser.data',
    'GALAXIES_MILKY_WAY': meson.current_source_dir() / '.data/galaxies/milky_way/galaxy.data',
    'GALAXIES_MILKY_WAY_FACTIONS_EARTH': meson.current_source_dir() / '.data/galaxies/milky_way/faction_earth.data',
    'GALAXIES_MILKY_WAY_FACTIONS_NEUTRAL': meson.current_source_dir() / '.data/galaxies/milky_way/faction_neutral.data',
    'GALAXIES_MILKY_WAY_FACTIONS_PIRATES': meson.current_source_dir() / '.data/galaxies/milky_way/faction_pirates.data',
    'GALAXIES_MILKY_WAY_ALPHA_CENTAURI': meson.current_source_dir() / '.data/galaxies/milky_way/system_alpha_centauri.data',
    'GALAXIES_MILKY_WAY_ALPHA_CENTAURI_STAR_ALPHA_CENTAURI': meson.current_source_dir() / '.data/galaxies/milky_way/star_alpha_centauri.data',
    'GALAXIES_MILKY_WAY_ALPHA_CENTAURI_PLANET_TAU_PRIME': meson.current_source_dir() / '.data/galaxies/milky_way/planet_tau_prime.data',
    'GALAXIES_MILKY_WAY_ALPHA_CENTAURI_PLANET_HEPHANT': meson.current_source_dir() / '.data/galaxies/milky_way/planet_hephant.data',
    'GALAXIES_MILKY_WAY_RIGEL': meson.current_source_dir() / '.data/galaxies/milky_way/system_rigel.data',
    'GALAXIES_MILKY_WAY_RIGEL_STAR_RIGEL': meson.current_source_dir() / '.data/galaxies/milky_way/star_rigel.data',
    'GALAXIES_MILKY_WAY_RIGEL_PLANET_RIGEL_GUARDIAN': meson.current_source_dir() / '.data/galaxies/milky_way/planet_rigel_guardian.data',
    'GALAXIES_MILKY_WAY_SOL': meson.current_source_dir() / '.data/galaxies/milky_way/system_sol.data',
    'GALAXIES_MILKY_WAY_SOL_STAR_SOL': meson.current_source_dir() / '.data/galaxies/milky_way/star_sol.data',
    'GALAXIES_MILKY_WAY_SOL_PLANET_EARTH': meson.current_source_dir() / '.data/galaxies/milky_way/planet_earth.data',
    'GALAXIES_MILKY_WAY_SOL_PLANET_MARS': meson.current_source_dir() / '.data/galaxies/milky_way/planet_mars.data',
    'GALAXIES_MILKY_WAY_SOL_PLANET_MOON': meson.current_source_dir() / '.data/galaxies/milky_way/planet_moon.data',
    'GALAXIES_MILKY_WAY_TICHEL': meson.current_source_dir() / '.data/galaxies/milky_way/system_tichel.data',
    'GALAXIES_MILKY_WAY_TICHEL_STAR_TICHEL': meson.current_source_dir() / '.data/galaxies/milky_way/star_tichel.data',
    'GENERATOR_CLASSES_SMALL_GENERATOR': meson.current_source_dir() / '.data/generator_class_small_generator.data',
    'MESHES_CARGO_CUBE': meson.current_source_dir() / '.data/mesh_cargo_cube.data',
    'MESHES_FIGHTER_COCKPIT': meson.current_source_dir() / '.data/mesh_fighter_cockpit.data',
    'MESHES_FIGHTER_FACTION': meson.current_source_dir() / '.data/mesh_fighter_faction.data',
    'MESHES_FIGHTER_HULL': meson.current_source_dir() / '.data/mesh_fighter_hull.data',
    'MESHES_GAUSS_SHELL': meson.current_source_dir() / '.data/mesh_gauss_shell.data',
    'MESHES_LASER_SHOT': meson.current_source_dir() / '.data/mesh_laser_shot.data',
    'MESHES_LIGHT_BATTERY': meson.current_source_dir() / '.data/mesh_light_battery.data',
    'MESHES_LIGHT_GAUSS_AMMUNITION': meson.current_source_dir() / '.data/mesh_light_gauss_ammunition.data',
    'MESHES_LIGHT_GAUSS_CANNON': meson.current_source_dir() / '.data/mesh_light_gauss_cannon.data',
    'MESHES_LIGHT_LASER': meson.current_source_dir() / '.data/mesh_light_laser.data',
    'MESHES_LIGHT_LASER_TURRET_BASE': meson.current_source_dir() / '.data/mesh_light_laser_turret_base.data',
    'MESHES_LIGHT_LASER_TURRET_GUN': meson.current_source_dir() / '.data/mesh_light_laser_turret_gun.data',
    'MESHES_PLANET': meson.current_source_dir() / '.data/mesh_planet.data',
    'MESHES_SHUTTLE_FACTION': meson.current_source_dir() / '.data/mesh_shuttle_faction.data',
    'MESHES_SHUTTLE_HULL': meson.current_source_dir() / '.data/mesh_shuttle_hull.data',
    'MESHES_SMALL_GENERATOR': meson.current_source_dir() / '.data/mesh_small_generator.data',
    'MESHES_TRANSPORTER_FACTION': meson.current_source_dir() / '.data/mesh_transporter_faction.data',
    'MESHES_TRANSPORTER_HULL': meson.current_source_dir() / '.data/mesh_transporter_hull.data',
    'MODELS_CARGO_CUBE': meson.current_source_dir() / '.data/model_cargo_cube.data',
    'MODELS_FIGHTER': meson.current_source_dir() / '.data/model_fighter.data',
    'MODELS_GAUSS_SHELL': meson.current_source_dir() / '.data/model_gauss_shell.data',
    'MODELS_LASER_SHOT': meson.current_source_dir() / '.data/model_laser_shot.data',
    'MODELS_LIGHT_BATTERY': meson.current_source_dir() / '.data/model_light_battery.data',
    'MODELS_LIGHT_GAUSS_AMMUNITION': meson.current_source_dir() / '.data/model_light_gauss_ammunition.data',
    'MODELS_LIGHT_GAUSS_CANNON': meson.current_source_dir() / '.data/model_light_gauss_cannon.data',
    'MODELS_LIGHT_LASER': meson.current_source_dir() / '.data/model_light_laser.data',
    'MODELS_LIGHT_LASER_TURRET': meson.current_source_dir() / '.data/model_light_laser_turret.data',
    'MODELS_PLANET': meson.current_source_dir() / '.data/model_planet.data',
    'MODELS_SHUTTLE': meson.current_source_dir() / '.data/model_shuttle.data',
    'MODELS_SMALL_GENERATOR': meson.current_source_dir() / '.data/model_small_generator.data',
    'MODELS_TRANSPORTER': meson.current_source_dir() / '.data/model_transporter.data',
    'PROGRAMS_DEFAULT': meson.current_source_dir() / '.data/program_default.data',
    'PROGRAMS_FLAT': meson.current_source_dir() / '.data/program_flat.data',
    'PROGRAMS_FONT': meson.current_source_dir() / '.data/program_font.data',
    'PROGRAMS_FONT_WITHOUT_CLIPPING': meson.current_source_dir() / '.data/program_font_without_clipping.data',
    'PROGRAMS_NO_LIGHTING': meson.current_source_dir() / '.data/program_no_lighting.data',
    'PROGRAMS_PARTICLE': meson.current_source_dir() / '.data/program_particle.data',
    'PROGRAMS_UI_TEXTURE': meson.current_source_dir() / '.data/program_ui_texture.data',
    'PROGRAMS_WIDGET': meson.current_source_dir() / '.data/program_widget.data',
    'SCENARIOS_NEW_GAME': meson.current_source_dir() / '.data/scenario_new_game.data',
    'SCENARIOS_RICH_GAME': meson.current_source_dir() / '.data/scenario_rich_game.data',
    'SCENARIOS_RIGEL_SPECTATOR': meson.current_source_dir() / '.data/scenario_rigel_spectator.data',
    'SETTINGS_KEY_BINDING_PROFILE': meson.current_source_dir() / '.data/setting_key_binding_profile.data',
    'SETTINGS_WINDOW_DIMENSIONS': meson.current_source_dir() / '.data/setting_window_dimensions.data',
    'SHADERS_DEFAULT_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_default.data',
    'SHADERS_DEFAULT_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_default.data',
    'SHADERS_FLAT_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_flat.data',
    'SHADERS_FLAT_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_flat.data',
    'SHADERS_FONT_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_font.data',
    'SHADERS_FONT_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_font.data',
    'SHADERS_FONT_WITHOUT_CLIPPING_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_font_without_clipping.data',
    'SHADERS_NO_LIGHTING_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_no_lighting.data',
    'SHADERS_NO_LIGHTING_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_no_lighting.data',
    'SHADERS_PARTICLE_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_particle.data',
    'SHADERS_PARTICLE_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_particle.data',
    'SHADERS_UI_TEXTURE_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_ui_texture.data',
    'SHADERS_UI_TEXTURE_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_ui_texture.data',
    'SHADERS_WIDGET_FRAGMENT_SHADER': meson.current_source_dir() / '.data/fragment_shader_widget.data',
    'SHADERS_WIDGET_VERTEX_SHADER': meson.current_source_dir() / '.data/vertex_shader_widget.data',
    'SHIP_CLASSES_FIGHTER': meson.current_source_dir() / '.data/ship_class_fighter.data',
    'SHIP_CLASSES_SHUTTLE': meson.current_source_dir() / '.data/ship_class_shuttle.data',
    'SHIP_CLASSES_TRANSPORTER': meson.current_source_dir() / '.data/ship_class_transporter.data',
    'SLOT_CLASSES_LIGHT_BATTERY': meson.current_source_dir() / '.data/slot_class_light_battery.data',
    'SLOT_CLASSES_LIGHT_TURRET': meson.current_source_dir() / '.data/slot_class_light_turret.data',
    'SLOT_CLASSES_LIGHT_WEAPON': meson.current_source_dir() / '.data/slot_class_light_weapon.data',
    'SLOT_CLASSES_MEDIUM_WEAPON': meson.current_source_dir() / '.data/slot_class_medium_weapon.data',
    'SLOT_CLASSES_SMALL_GENERATOR': meson.current_source_dir() / '.data/slot_class_small_generator.data',
    'TEXTURES_FONT': meson.current_source_dir() / '.data/texture_font.data',
    'TEXTURES_PARTICLE': meson.current_source_dir() / '.data/texture_particle.data',
    'TURRET_CLASSES_LIGHT_LASER_TURRET': meson.current_source_dir() / '.data/turret_class_light_laser.data',
  }
)

manifest_json = configure_file(
  configuration: manifest_json_configuration,
  input: 'manifest.json.in',
  output: 'manifest.json',
)

custom_target(
  'data.arx',
  build_by_default: true,
  output: 'data.arx',
  command: [
    python3_program,
    arxbuild_py_script,
    '--manifest',
    manifest_json,
    '--output',
    '@OUTPUT@'
  ]
)
