root = ../..

default: all

all: all-recursive

all-here: 

all-recursive: all-here

clean: clean-recursive

clean-here: 

clean-recursive: clean-here

.PHONY: all all-here all-recursive clean clean-here clean-recursive default
